version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: smart-mongo
    restart: always
    ports:
      - "27018:27017" # host:container
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./Backend
    container_name: smart-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env # contains Cloudinary and other variables
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mongo

volumes:
  mongo_data:
